name: Call AWS Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: ani7546/reusable-workflow-repo/.github/workflows/deploy.yml@main
    with:
      source: "."  # Deploy all files from the repository root
      target: "~/manual-directory"
    secrets:
      AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
      AWS_IP: ${{ secrets.AWS_IP }}
      AWS_USER: ${{ secrets.AWS_USER }}
