name: Call Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Set the secret as an environment variable

    uses: ani7546/reusable-workflow-repo/.github/workflows/deploy.yml@main
    with:
      server_ip: 3.109.202.45
      ssh_user: ubuntu
